apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: devopszon-httpapi-host-eventsource
  namespace: argo-events
  labels:
    app: devopszon-httpapi-host
    project-id: 3a1d6f64-5897-e03b-c4de-b5e698301e9a
    service: devopszon-httpapi-host
    managed-by: devopszon
    target-namespace: devopszon
spec:
  # BEST PRACTICE: Watch only POD events for maximum stability
  # Pod events capture deployment updates, scaling, crashes, etc.
  # Based on: https://github.com/argoproj/argo-events/tree/stable/examples
  
  # Template for EventSource pods
  # FIX: Add securityContext and resources to prevent "too many open files"
  template:
    # PRODUCTION FIX: Init container to increase file descriptor limits
    # Prevents "too many open files" errors in production
    initContainers:
    - name: increase-limits
      image: busybox:latest
      command:
      - sh
      - -c
      - |
        echo "Increasing file descriptor limits for EventSource stability..."
        ulimit -n 65536 || true
        sysctl -w fs.inotify.max_user_instances=8192 || true
        sysctl -w fs.inotify.max_user_watches=524288 || true
        echo "File descriptor limits increased successfully"
      securityContext:
        privileged: true
    container:
      securityContext:
        capabilities:
          add:
          - SYS_RESOURCE  # Allow changing ulimit
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
  
  resource:
    pods:
      version: v1
      resource: pods
      namespace: devopszon
      filter:
        labels:
          - key: service
            operation: ==
            value: devopszon-httpapi-host
      eventTypes:
        - ADD     # New pod created
        - UPDATE  # Pod status changed (Running → CrashLoopBackOff, etc.)
        - DELETE  # Pod terminated
