apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devopszon-httpapi-host
  namespace: devopszon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopszon-httpapi-host
  maxReplicas: 1
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80